spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

management:
  endpoint:
    beans:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
